title: "Pursuit of Conscious Incompetence"
email: Anthony8Lee@Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aoot.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Anthony Lee # add your name
author-pic: AnthonyHeadshot_Cropped.jpg
about-author: #My name is Adam Neilson. I’m a full-time adventure travel blogger and photographer who’s been exploring the world for over 2 years.

# Contact links
email: "Anthony8Lee@Gmail.com" # Add your Email address
phone: "+1-281-673-5455" # Add your Phone number
website: "aoot.github.io" # Add your website, do not add http://
linkedin: "anthonyylee" # Add your Linkedin handle
github: "Aoot" # Add your Github handle
twitter: "Antmaker" # Add your Twitter handle
facebook: "Anthony8Lee" # Add your Facebook handle
instagram: "Antmaker" # Add your Instagram handle
# pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: anthonys-blog # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

theme: jekyll-theme-cayman
